fix(status): public path appearing as 'undefined'
webpack/webpack-dev-server pull request #2728
Opened 2020-09-02 14:41 UTC by cshawaus

- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

No

### Motivation / Use-Case

Instead of:

```bash
webpack output is served from undefined
```

The correct public path for webpack 5 will be shown:

```bash
webpack output is served from /
```

### Breaking Changes

No

### Additional Info

n/a

2020-09-02 15:49 UTC, evilebottnawi requested changes
Invalid fix, please provide reproducible test repo

2020-09-02 15:55 UTC, cshawaus commented
> Invalid fix, please provide reproducible test repo


https://github.com/cshawaus/vue-3-ts-demo/tree/webpack-5

2020-09-03 11:24 UTC, evilebottnawi commented
@cshawaus I will look at this in near future

2020-11-27 16:11 UTC, ylemkimon commented
Fixed in #2849.

2020-11-27 16:14 UTC, alexander-akait commented
@ylemkimon yep, anyway I think we should improve this, because `publicPath` can be `auto` or can be `Function`, maybe we should move it in plugin :thinking:

2021-01-18 17:31 UTC, alexander-akait commented
Fixed in master

2021-01-18 17:31 UTC, closed without merging